require: rubocop-rspec

AllCops:
  Exclude:
    - 'lib/client_auth.rb'
    - 'vendor/**/*'
  TargetRubyVersion: 2.3

Metrics/LineLength:
  Max: 95
Metrics/BlockLength:
  Max: 150

Style/Documentation:
  Enabled: false

Style/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Style/FrozenStringLiteralComment:
  Enabled: false

RSpec/VerifiedDoubles:
  IgnoreSymbolicNames: true
